### ISSUE TITLE
ur code looks very similar to Sqlmap!

### ISSUE THREAD

**Issue by darkr4y** [Ekultek/WhatWaf#2]
for eg.

[https://github.com/Ekultek/WhatWaf/blob/master/content/plugins/360.py](https://github.com/Ekultek/WhatWaf/blob/master/content/plugins/360.py)

[https://github.com/sqlmapproject/sqlmap/blob/master/waf/360.py](https://github.com/sqlmapproject/sqlmap/blob/master/waf/360.py)

never copy and paste ;)
and you should show the source where your code are ship from.

**Comment by Ekultek** [comment]
Alright, I knew some douchebag was going to say something about this. So lets go ahead and just get this little bitch fest under control.

1. Of course it looks similiar, it's literally doing the EXACT SAME THING that sqlmaps WAF detection scripts are doing, with a key difference. It tells you what bypasses work.
2. Are you accusing me of copy and pasting from sqlmap into whatwaf? If you are, then you also need to accuse the same from wafw00f for both sqlmap and myself:
   - [sqlmap](https://github.com/sqlmapproject/sqlmap/blob/master/waf/barracuda.py)
   - [wafw00f](https://github.com/EnableSecurity/wafw00f/blob/master/wafw00f/plugins/barracuda.py)
   - [whatwaf](https://github.com/Ekultek/WhatWaf/blob/master/content/plugins/barracuda.py)
3. Just go use a different tool. If you make a comment or an issue again, it will probably end up closed. 
4. `and you should show the source where your code are ship from.` My code shipped from my house, so I'm not going to be showing you my house anytime soon. If you are saying prove where you got the information for the regular expression, try going to the manufacturer website, and you can talk to the representatives for three hours each trying to get some sort of HTML sample so you can see what it looks like.

Now having said all that. Thank you for bringing up a pointless issue that has absolutely no relevance to any situation on whatwaf. If you want to actually be useful, find a flaw in it and fix it.

So lets recap:
 - Yes it looks similar because it does the SAME THING (I thought that would be a given?)
 - No I didn't copy and paste, it just turns out that the expressions given are ones that work

Thanks for using whatwaf, have a good day bud.

**Comment by Ekultek** [comment]
On second thought, I'll give you some time for a rebuttal. I would love to see what you have to say

**Comment by Ekultek** [comment]
I never mentioned anything about a small dick in this comment my little friend. I see your little ego is showing though. <3
