### ISSUE TITLE
specify a custom tamper directory

### ISSUE THREAD

**Issue by jesuiscamille** [Ekultek/WhatWaf#62]
It would be nice if WhatWaf would be able to specify a different tamper directory, to allow integration with other tools ( thinking about our beloved [sqlmap](https://github.com/sqlmapproject/sqlmap) )

# Exemple:

`./whatwaf.py --tamper-dir=/path/to/sqlmap/tampers/directory`

**Comment by Ekultek** [comment]
what if the tampers aren't compatible with whatwaf?

**Comment by jesuiscamille** [comment]
The user/script should make sure that the tamper he provides are conforming to what WhatWaf expects (a python file with a `tamper(payload, **kwargs)` func which returns the tampered payload).
Also, sqlmap tampers api seems to be the same as WhatWaf.

**Comment by Ekultek** [comment]
Why would you just not add your tampers to the whatwaf directory then?

**Comment by jesuiscamille** [comment]
Because that's not user-friendly. Per example, if a user pull the latest sqlmap release to get new tampers, he would have to copy over again all sqlmap's tampers to WhatWaf's tampers directory.

**Comment by Ekultek** [comment]
why am i worried about user friendliness? If you don't know how to do it, you shouldn't be using it

**Comment by jesuiscamille** [comment]
Actually, I know how to use WhatWaf thanks for your recommendation. If I open these issues, it's to give ideas about how WhatWaf could be improved in an external point of view.

Not to get them rejected with something like "Why the fuck should this be implemented, we already can use this ugly and complicated method".

You've created a nice tool. Now, I would like to know why you don't want it to be user-friendly when the persons who uses it are primarily users.

**Comment by Ekultek** [comment]
this is not a bad idea, so don't get it twisted. it's jut going to cause more harm then good.

**Comment by jesuiscamille** [comment]
You're right.

**Comment by Ekultek** [comment]
example..

if someone has a directory full of tamper scripts and pass the flag, without parsing the tamper scripts first there is not way to identify if the tampers have the correct information on them. Such as:

```
__example_payload__
# or
__description__
```

Or to tell if the script has the correct keywords or not:

```
def tamper(content, **kwargs): pass
```

If for any reason, one of these thing isn't in the script, the program will fail, and it will fall back on me to fix it because I created the "use your own tampers" functionality for the program. If you can design a full proof method to get this done, by all means feel free to do so and make a pull request. But I don't feel comfortable enough to make a "fool proof" method for it. 

Even if we decided to make a Wiki section about how to make tamper scripts, how many of the users are actually going to read the documentation for it?

**Comment by Ekultek** [comment]
Gonna try to create one or no?

**Comment by jesuiscamille** [comment]
I'm actually trying to implement --tamper-dir in [this branch](https://github.com/jesuiscamille/WhatWaf/tree/tamper-dir), and that's damn hard.

At this moment, I'm trying to import files by their paths ^^'

**Comment by jesuiscamille** [comment]
Okay, so this takes too much time. I think I'm just gonna drop it for now and edit one by one all the sqlmap tampers.

**Comment by Ekultek** [comment]
Alright as of now with https://github.com/Ekultek/WhatWaf/commit/9b248377f3f1d909b8d3a70f77a49af4bcdc3964 all you need to do is make sure that the path is sent to the ScriptQueue class. Should be fairly simple now
