### ISSUE TITLE
copyright problems (sqlmap)

### ISSUE THREAD

**Issue by stamparm** [Ekultek/WhatWaf#73]
https://github.com/Ekultek/WhatWaf/tree/master/content/tampers and https://github.com/Ekultek/WhatWaf/tree/master/content/plugins are copies from https://github.com/sqlmapproject/sqlmap/tree/master/tamper and https://github.com/sqlmapproject/sqlmap/tree/master/waf while removing the copyright headers.

GPL doesn't work like that. You can't just blindly copy something while removing the original authors copyright notice. Good reference: https://stackoverflow.com/a/4475348

**Comment by Ekultek** [comment]
Hi @stamparm, the copyright applies to you only if it was, as stated, blindly copied. The only thing I can see that would qualify in this case would be the [booleanmask](https://github.com/Ekultek/WhatWaf/blob/master/content/tampers/booleanmask.py) tamper, because it is extremely similar to yours, if you would like I can go ahead and refactor it to make it different then yours, so that it works similarly but not exactly the same? Your call.

**Comment by stamparm** [comment]
You are joking, right? You've copy-pasted everything, removed the things that you don't need and removed the copyright notice. Please don't play dumb.

GPL says that you can do whatever you want with the code, but there has to be the original copyright notice OR at least "based on" notice.

If you'll play hard I have two choices:

1) Contact Github directly to ask for their opinion
2) Go publicly with the statement that you've stolen the code AND leave it to the public to decide whether I am right or not
or
3) You can just take back the copyright notice AND put your name at the top as the person who is currently taken care of the code inside your repository

p.s. please don't play dump. You know that I don't have tolerance for this kind of pretending

**Comment by stamparm** [comment]
p.s. even you've left the original names of the WAF and tamper scripts :) Dear Lord, I am not sure how hard you have to play dumb and say `the copyright applies to you only if it was, as stated, blindly copied`.

GPL says that you have to put the original copyright notice EVEN if the code is JUST based on the original project

**Comment by stamparm** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html

```
If you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.
```

**Comment by stamparm** [comment]
http://wpandlegalstuff.com/understanding-gpl-licensing-wordpress/

```
Modifications / derivative works: You may modify the Program or any part of it and distribute
the modifications or new work as long as modified files contain notices regarding the existence
and date of changes and any work that you distribute or publish that contains or is derived from
the Program or any part of it is licensed as a whole at no charge to all third parties under the GPL.
```

https://stackoverflow.com/a/5696904

```
The GPL ensures you still get credit. Modifiers are required to retain your copyright
statements.
```

**Comment by stamparm** [comment]
I'll choose 4) as I don't want to loose my nerves.

4) You are not welcome anymore to the @sqlmap. Please don't comment anything there anymore as everything will be invalidated. Plagiarizing other people's work, without giving credits is the lowest form of "programming". Just putting a DUMB reference would prevent all this mess.

**Comment by Ekultek** [comment]
So do we need to to get into wafw00f? I’m in the process of editing what could be considered copied.

**Comment by stamparm** [comment]
p.p.s. this is just our example how normal people (real PROGRAMMERS) deal with this kind of stuff:

* https://github.com/sqlmapproject/sqlmap/blob/master/LICENSE#L34-L35

```
This license does not apply to the third-party components. More details can
be found inside the file 'doc/THIRD-PARTY.md'.
```

---

* https://github.com/sqlmapproject/sqlmap/blob/master/doc/THIRD-PARTY.md

![123](https://user-images.githubusercontent.com/921555/40940682-deaf3470-6848-11e8-94fc-205651563f7a.png)

---

* https://github.com/sqlmapproject/sqlmap/blob/master/thirdparty/ansistrm/ansistrm.py#L2
* https://github.com/sqlmapproject/sqlmap/blob/master/thirdparty/beautifulsoup/beautifulsoup.py#L45
* https://github.com/sqlmapproject/sqlmap/blob/master/thirdparty/bottle/bottle.py#L12
etc.

---

p.p.p.s. @Ekultek as said, you don't have to do any re-modifications. I've decided. You are not welcome to the @sqlmapproject any more

**Comment by Ekultek** [comment]
Alright, since you're going to come to my project and start talking shit. Lets just do it right now;

 - [wafwoof](https://github.com/EnableSecurity/wafw00f/blob/master/wafw00f/plugins/wallarm.py)|[sqlmap](https://github.com/sqlmapproject/sqlmap/blob/master/waf/wallarm.py) 
 - [wafw00f](https://github.com/EnableSecurity/wafw00f/blob/master/wafw00f/plugins/uspses.py)|[sqlamp](https://github.com/sqlmapproject/sqlmap/blob/master/waf/uspses.py)
 - [wafw00f](https://github.com/EnableSecurity/wafw00f/blob/master/wafw00f/plugins/teros.py)|[sqlmap](https://github.com/sqlmapproject/sqlmap/blob/master/waf/teros.py)

Do I need to continue? Don't come and try to cause trouble when it's clear you have blatantly copied wafw00f in the first place.

Just in case you missed it, [here](https://github.com/EnableSecurity/wafw00f/blob/master/LICENSE) is wafw00f's license (you should probably read it). 

I do not give a flying fuck if I am not welcome at @sqlmapproject anymore. Thank you for your time and your concerns, I will edit what can be taken as _copied_ and you can go about your way and be a _real_ programmer who had to take a project from someone else to feel important about themselves. Good luck in your future endeavors.

**Comment by Ekultek** [comment]
I think you already lost your nerves lol

**Comment by stamparm** [comment]
My last comment to @Ekultek. You've posted references to wafw00f and sqlmap, while not checking the commit history of those scripts. You would be surprised with the dates.

**Comment by Ekultek** [comment]
@stamparm So that scratches one of them off the list. I can keep going. Look dude, it's not worth fighting about, especially with you because you just love to be a dick at all times for some reason (I have a feeling it's because you have a _Really_ small penis, but you know I'm not a judgemental man) so whether you want to continue that's on you, feel free to keep bitching. However, I understand your point that you where trying to make (by reading between your verbal threats and what not) and I, as I've stated multiple times, am in the process of editing. So if you wanna be civil (for once) we can. If not, please go fuck yourself with a cactus. Later homes.
